[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"
via_ir = true
optimizer = true

# Etherscan configuration
[profile.default.etherscan]
unknown_chain = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
