global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ponder"
    static_configs:
      - targets: ["api.ethcomments.xyz"]
    metrics_path: "/metrics"

  - job_name: "indexer"
    static_configs:
      - targets: ["api.ethcomments.xyz"]
    metrics_path: "/api/internal/metrics"

  - job_name: "ecp-channel-builder"
    static_configs:
      - targets: ["builder.ethcomments.xyz"]
    metrics_path: "/api/metrics"
    bearer_token_file: /etc/prometheus/bearer_token
